version: '3.7'

services:
  app:
    build: .
    command: FLASK_ENV=development
    command: FLASK_ENV=app
    command: FLASK_ENV=run.py
    command: flask run --host=0.0.0.0
    ports:
      - 5000:5000