version: '3.7'

services:
  app:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/usr/src/app/
    ports:
      - 5000:5000
    env_file: 
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: 
      - ./.env

volumes:
  postgres_data: